#!/usr/bin/env python

import sys, os, re, json

search_results = []

if len(sys.argv) > 1:
    query = sys.argv[1]

    if len(query) > 0:
        bookmark_parts = os.popen("cat ~/.config/google-chrome/Default/Bookmarks | egrep '(^\s*\"name\"|^\s*\"url\")'").read()
        bookmarks = []
        bookmark = {}
        bookmark_parts = iter(bookmark_parts.splitlines())

        for bookmark_part in bookmark_parts:

            if '"name"' in bookmark_part:
                bookmark_part = re.sub('^\s* "name":\s*', "", bookmark_part)
                bookmark["name"] = bookmark_part[1:-2]

            if '"url"' in bookmark_part:
                bookmark_part = re.sub('^\s* "url":\s*', "", bookmark_part)
                bookmark["url"] = bookmark_part[1:-1]
                bookmarks.append(bookmark)
                bookmark = {}

        search_results = []

        for bookmark in bookmarks:
            if query.lower() in bookmark["name"].lower() or query.lower() in bookmark["url"]:
                result = {
                    "name": bookmark["name"] + "",
                    "command": os.path.dirname(os.path.realpath(__file__)) + "/../bin/open_file " + bookmark["url"],
                    "icon": "google-chrome"
                }
                search_results.append(result)


print json.dumps(search_results)